[package]
name = "lighthouse-lang-go"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
tree-sitter-go.workspace = true
lighthouse-model.workspace = true
lighthouse-plugin.workspace = true
lighthouse-syntax.workspace = true

[dev-dependencies]
tempfile.workspace = true
