[package]
name = "lighthouse-syntax"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
tree-sitter.workspace = true
lighthouse-model.workspace = true
streaming-iterator.workspace = true

[dev-dependencies]
tree-sitter-go.workspace = true
