//! The reference of the fix operations, generated into the docs from the same
//! table that documents the schema: what each operation takes and means.

use std::fmt::Write;

const NOTICE: &str = "<!-- Generated by `lighthouse docs generate`. Do not edit. -->";

const WHEN: Param = Param {
    name: "when",
    ty: "CEL bool",
    required: false,
    description: "Skips the operation when false.",
};

/// The operations a `fix: { ops: [...] }` may list.
pub const OPERATIONS: &[Operation] = &[
    Operation {
        name: "move",
        summary: "Relocates a declaration, with its leading doc comments and attributes, \
                  next to another one. Both must live in the same container (the same \
                  file level, the same impl or class body); the blank-line separation \
                  of the moved block is kept.",
        params: &[
            Param {
                name: "node",
                ty: "CEL symbol id",
                required: true,
                description: "The declaration to move.",
            },
            Param {
                name: "before",
                ty: "CEL symbol id",
                required: false,
                description: "Place the declaration right before this one. Exactly one of `before` and `after`.",
            },
            Param {
                name: "after",
                ty: "CEL symbol id",
                required: false,
                description: "Place the declaration right after this one.",
            },
            WHEN,
        ],
        example: "- op: move\n  node: finding.evidence.callee\n  after: finding.evidence.caller",
    },
    Operation {
        name: "reorder",
        summary: "Sorts the declarations of a container by order keys, stably: a \
                  declaration moves only as far as the keys demand, and declarations \
                  a key does not order stay in the place they occupy. The first key \
                  decides, the next ones break ties.",
        params: &[
            Param {
                name: "scope",
                ty: "`file` or `owner`",
                required: true,
                description: "`file`: every declaration of the finding's file; each container (the file level, an `impl` or class body) is sorted on its own. `owner`: only the members of the finding symbol's owner.",
            },
            Param {
                name: "by",
                ty: "list of order keys",
                required: true,
                description: "Registered keys, `plugin/name`; the table below lists them.",
            },
            WHEN,
        ],
        example: "- op: reorder\n  scope: file\n  by: [design/group]",
    },
    Operation {
        name: "delete",
        summary: "Removes a declaration with its extent, or a range of text such as a \
                  comment. A range that fills whole lines takes the lines, and one \
                  blank line when that would leave two.",
        params: &[
            Param {
                name: "node",
                ty: "CEL symbol id",
                required: false,
                description: "The declaration to remove. Either `node`, or `file` and `span`.",
            },
            Param {
                name: "file",
                ty: "CEL string",
                required: false,
                description: "Project-relative path of the range's file.",
            },
            Param {
                name: "span",
                ty: "CEL span",
                required: false,
                description: "`{start: {line, col}, end: {line, col}}`, 1-based, columns in bytes, end exclusive.",
            },
            WHEN,
        ],
        example: "- op: delete\n  file: finding.file\n  span: finding.span",
    },
    Operation {
        name: "rename",
        summary: "Renames a symbol at its declaration and at every reference site. \
                  Declined unless the provider reports reference sites and every \
                  reference edge to the symbol is semantic.",
        params: &[
            Param {
                name: "symbol",
                ty: "CEL symbol id",
                required: true,
                description: "The symbol to rename.",
            },
            Param {
                name: "name",
                ty: "template",
                required: true,
                description: "The new name; `{{ cel }}` holes are replaced.",
            },
            WHEN,
        ],
        example: "- op: rename\n  symbol: finding.symbol\n  name: '{{ symbol.name }}Value'",
    },
    Operation {
        name: "replace",
        summary: "Replaces a range of text; an empty range inserts. The escape hatch \
                  for what the other operations do not state.",
        params: &[
            Param {
                name: "file",
                ty: "CEL string",
                required: true,
                description: "Project-relative path.",
            },
            Param {
                name: "span",
                ty: "CEL span",
                required: true,
                description: "The range to replace.",
            },
            Param {
                name: "text",
                ty: "template",
                required: true,
                description: "The new text; `{{ cel }}` holes are replaced.",
            },
            WHEN,
        ],
        example: "- op: replace\n  file: finding.file\n  span: finding.span\n  text: '// {{ finding.evidence.label }}'",
    },
];

/// One parameter of a fix operation.
pub struct Param {
    pub name: &'static str,
    pub ty: &'static str,
    pub required: bool,
    pub description: &'static str,
}

/// One generic fix operation.
pub struct Operation {
    pub name: &'static str,
    pub summary: &'static str,
    pub params: &'static [Param],
    pub example: &'static str,
}

/// The page of the fix operations. `keys` are the registered order keys with
/// their descriptions.
pub fn fix_operations_markdown(keys: &[(String, String)]) -> String {
    let mut out = format!(
        "{NOTICE}\n\n# Fix operations\n\n\
         A decision's `fix:` block says how the findings of its rule are fixed. Its \
         `type` is one of `ops`, `command` and `rpc`; it carries a `safety` cap, and \
         may list the provider capabilities it `requires`:\n\n\
         ```yaml\nfix:\n  safety: safe        # safe | suggested\n  requires: [extent]  # optional\n  type: ops           # ops | command | rpc\n  ops: [...]\n```\n\n\
         The `ops` type is a list of the generic operations below. Operations state \
         edits over code-model nodes; the orchestrator lowers them to text edits with \
         the spans the language provider reports, formats, re-checks and rolls back \
         what gets worse. Expressions are CEL over `finding` (`rule`, `message`, \
         `file`, `span`, `symbol`, `evidence`, `fingerprint`, `facts`), `symbol` (the \
         finding's symbol, as in declarative rules) and `options` (the options the \
         rule ran with). Every operation also takes `when` (CEL bool): the \
         operation is skipped when it is false.\n\n"
    );
    for op in OPERATIONS {
        let _ = write!(out, "## `{}`\n\n{}\n\n", op.name, op.summary);
        let _ = writeln!(out, "| param | type | meaning |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for p in op.params.iter().filter(|p| p.name != WHEN.name) {
            let required = if p.required { ", required" } else { "" };
            let _ = writeln!(
                out,
                "| `{}` | {}{required} | {} |",
                p.name, p.ty, p.description
            );
        }
        let _ = write!(out, "\n```yaml\n{}\n```\n\n", op.example);
    }
    out.push_str("## Order keys\n\nKeys for `reorder.by`, registered by plugins.\n\n");
    let _ = writeln!(out, "| key | orders by |");
    let _ = writeln!(out, "| --- | --- |");
    for (id, description) in keys {
        let _ = writeln!(out, "| `{id}` | {description} |");
    }
    out.push_str(
        "\n## Commands\n\n\
         The `command` type is the simple text contract: a program, without a shell, on a \
         scratch copy of the finding's file. Structured data goes through `rpc`, not through \
         commands.\n\n\
         ```yaml\nfix:\n  safety: suggested\n  type: command\n  argv: [\"gofmt\", \"-s\", \"-w\", \"{file}\"]\n  output: in-place   # in-place | text\n  stdin: none        # none | file\n  env: {}            # extra variables\n  timeout: 30s\n  scope: file\n```\n\n\
         - **Exit codes:** `0` succeeds, with the result per `output`; an empty result changes \
         nothing. `1` declines, with the reason from stderr. `2` and above, a signal or a \
         timeout is an error: nothing is applied and the capped stderr goes into the notice.\n\
         - **Output:** `in-place` diffs the scratch copy against the original; `text` takes the \
         new text of the file from stdout, which carries only that. stderr is for people and \
         is never parsed.\n\
         - **stdin:** `none` (default) or `file`, the content of the target file.\n\
         - **Argv:** `{file}` (the scratch copy), `{line}`, `{symbol}` and `{rule}` fill a whole \
         argument each (`--out={file}` is refused, and so is a value that starts with `-`). The \
         program runs with the scratch directory as its working directory.\n\
         - **Environment:** cleared to `PATH`, `HOME`, `LANG` and `TMPDIR`, plus the declared \
         `env`, plus `LIGHTHOUSE_DECISION` (the finding as JSON: rule, file, line, symbol, \
         fingerprint, evidence), `LIGHTHOUSE_OPTIONS` (the rule's options as JSON) and \
         `LIGHTHOUSE_API_VERSION`.\n\
         - **Limits:** the timeout sends SIGTERM to the process group, then SIGKILL after a \
         grace period; stdout and stderr are capped.\n\
         - **Trust:** a command runs only in a project the user trusts (`lighthouse trust`), \
         whoever wrote it; the repository cannot grant trust itself.\n\n\
         The `rpc` type, a language plugin's own fix method, is reserved: it loads, and the \
         findings of its rule are declined as not yet supported.\n",
    );
    out
}
