//! The dense pack pages of the generated docs: an index per section, short
//! decisions as table rows, and a full entry only for decisions that need one.

use std::fmt::Write;

use similar::TextDiff;

use crate::{
    Content, Decision, Enforcement, Example, ExampleFile, ExampleKind, OptionsSchema, Pack, Section,
};

const NOTICE: &str = "<!-- Generated by `lighthouse docs generate`. Do not edit. -->";

/// Where the decision sources live, relative to a page in `docs/decisions/`.
const SOURCES: &str = "../../decisions";

const CONTEXT_LINES: usize = 2;

pub fn pack_markdown(pack: &Pack) -> String {
    let mut out = format!(
        "{NOTICE}\n\n# {}\n\n{}\n\n",
        pack.title,
        one_line(&pack.intro)
    );
    for section in &pack.sections {
        section_markdown(&mut out, pack, section);
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

/// A judgment or doc decision with nothing beyond its requirement.
pub(crate) fn is_row(decision: &Decision) -> bool {
    matches!(
        decision.enforcement,
        Enforcement::Judgment | Enforcement::Doc
    ) && decision
        .options
        .as_ref()
        .is_none_or(|o| o.properties.is_empty())
        && decision.examples.is_empty()
        && decision.exceptions.is_none()
        && decision.languages.values().all(|l| l.tuning.is_none())
        && decision.fix.is_none()
        && decision.citation.is_none()
        && !decision.strict
}

/// The GitHub heading anchor of `title`.
pub(crate) fn anchor(title: &str) -> String {
    title
        .to_lowercase()
        .chars()
        .filter_map(|c| match c {
            ' ' | '-' => Some('-'),
            c if c.is_alphanumeric() || c == '_' => Some(c),
            _ => None,
        })
        .collect()
}

/// One table per section: every decision with its enforcement and fix, and the
/// requirement of the ones that need no entry of their own.
fn section_markdown(out: &mut String, pack: &Pack, section: &Section) {
    let _ = write!(
        out,
        "## {}\n\n{}\n\n",
        section.title,
        one_line(&section.intro)
    );
    let _ = writeln!(out, "| id | title | enforcement | fix | requirement |");
    let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
    for decision in &section.decisions {
        let (id, requirement) = if is_row(decision) {
            (format!("`{}`", decision.id()), cell(&decision.requirement))
        } else {
            (
                format!("[`{}`](#{})", decision.id(), anchor(&decision.title)),
                String::new(),
            )
        };
        let fix = decision
            .fix
            .as_ref()
            .map_or_else(String::new, |fix| fix.safety.to_string());
        let _ = writeln!(
            out,
            "| {id} | {} | {} | {fix} | {requirement} |",
            cell(&decision.title),
            level(decision)
        );
    }
    out.push('\n');
    let dir = format!("{SOURCES}/{}/{}", pack.id, section.id);
    for decision in section.decisions.iter().filter(|d| !is_row(d)) {
        entry_markdown(out, decision, &dir);
    }
}

fn entry_markdown(out: &mut String, decision: &Decision, dir: &str) {
    let _ = writeln!(out, "### {}\n", decision.title);
    let mut meta = format!(
        "`{}` · {} · {}",
        decision.id(),
        decision.scope.subject,
        level(decision)
    );
    if let Some(fix) = &decision.fix {
        let _ = write!(meta, " · fix: {}", fix.safety);
    }
    if decision.strict {
        meta.push_str(" · strict");
    }
    let _ = writeln!(out, "{meta}\n");
    let _ = writeln!(out, "*{}*\n", one_line(&decision.intent));
    let _ = writeln!(out, "{}\n", decision.requirement.trim());
    if let Some(exceptions) = &decision.exceptions {
        let _ = writeln!(out, "Exceptions: {}\n", exceptions.trim());
    }
    for (language, spec) in &decision.languages {
        if let Some(text) = &spec.tuning {
            let _ = writeln!(out, "Tuning ({language}): {}\n", text.trim());
        }
    }
    if let Some(citation) = &decision.citation {
        let _ = writeln!(out, "Method: {}\n", citation.trim());
    }
    if let Some(options) = decision
        .options
        .as_ref()
        .filter(|o| !o.properties.is_empty())
    {
        options_table(out, decision, options);
    }
    examples_markdown(out, &decision.examples, dir);
}

fn options_table(out: &mut String, decision: &Decision, options: &OptionsSchema) {
    let _ = writeln!(out, "| option | default | meaning |");
    let _ = writeln!(out, "| --- | --- | --- |");
    for (name, property) in &options.properties {
        let mut default = format!("`{}`", property.default);
        for (language, spec) in &decision.languages {
            if let Some(value) = spec.options.get(name) {
                let _ = write!(default, "; {language}: `{value}`");
            }
        }
        let _ = writeln!(
            out,
            "| `{name}` | {default} | {} |",
            cell(&property.description)
        );
    }
    out.push('\n');
}

/// The canonical pair, the other languages as links or names.
fn examples_markdown(out: &mut String, examples: &[Example], dir: &str) {
    let Some(invalid) = pick(examples, ExampleKind::Invalid, None) else {
        return;
    };
    let language = &invalid.language;
    if invalid.fixed.is_empty() {
        let valid = pick(examples, ExampleKind::Valid, Some(language));
        example_block(out, invalid, valid);
        if let Some(valid) = valid {
            example_block(out, valid, Some(invalid));
        }
    } else {
        diff_block(out, invalid);
    }
    let mut others: Vec<&str> = Vec::new();
    for example in examples {
        if example.language != *language && !others.contains(&example.language.as_str()) {
            others.push(&example.language);
        }
    }
    if !others.is_empty() {
        let list: Vec<String> = others
            .iter()
            .map(|other| language_links(examples, other, dir))
            .collect();
        let _ = writeln!(out, "Also: {}\n", list.join(", "));
    }
}

/// The canonical example of `kind`, else the first; of `language` when given.
fn pick<'a>(
    examples: &'a [Example],
    kind: ExampleKind,
    language: Option<&str>,
) -> Option<&'a Example> {
    let of_kind = || {
        examples
            .iter()
            .filter(move |e| e.kind == kind && language.is_none_or(|l| e.language == l))
    };
    of_kind().find(|e| e.canonical).or_else(|| of_kind().next())
}

/// The files of `example` that differ from `other`'s: boilerplate both sides
/// share (a manifest, an unchanged source file) is left out.
fn example_block(out: &mut String, example: &Example, other: Option<&Example>) {
    let many = example.files.len() > 1;
    let differs = |file: &&ExampleFile| {
        other.is_none_or(|other| {
            other
                .files
                .iter()
                .all(|o| o.path != file.path || o.text() != file.text())
        })
    };
    let mut files: Vec<&ExampleFile> = example.files.iter().filter(differs).collect();
    if files.is_empty() {
        files = example.files.iter().collect();
    }
    for file in files {
        let label = if many {
            format!("{} {}", example.kind, file.path)
        } else {
            example.kind.to_string()
        };
        let _ = writeln!(
            out,
            "```{} {label}\n{}\n```\n",
            example.language,
            file.text().trim_end()
        );
    }
}

fn diff_block(out: &mut String, example: &Example) {
    for fixed in &example.fixed {
        let before = example
            .files
            .iter()
            .find(|f| f.path == fixed.path)
            .map_or("", ExampleFile::text);
        let (before, after) = (with_newline(before), with_newline(fixed.text()));
        let diff = TextDiff::from_lines(&before, &after)
            .unified_diff()
            .context_radius(CONTEXT_LINES)
            .header(&format!("a/{}", fixed.path), &format!("b/{}", fixed.path))
            .to_string();
        let _ = writeln!(out, "```diff\n{}\n```\n", diff.trim_end());
    }
}

/// `go` alone for inline examples, `go ([invalid](..), [valid](..))` for files.
fn language_links(examples: &[Example], language: &str, dir: &str) -> String {
    let links: Vec<String> = examples
        .iter()
        .filter(|e| e.language == language)
        .filter_map(|example| {
            let source = example.files.iter().find_map(|file| match &file.content {
                Content::File(source) => Some(source),
                Content::Inline(_) => None,
            })?;
            Some(format!("[{}]({dir}/{source})", example.kind))
        })
        .collect();
    if links.is_empty() {
        language.to_owned()
    } else {
        format!("{language} ({})", links.join(", "))
    }
}

fn with_newline(text: &str) -> String {
    format!("{}\n", text.trim_end())
}

fn level(decision: &Decision) -> String {
    decision.severity().map_or_else(
        || decision.enforcement.to_string(),
        |severity| format!("{}→{severity}", decision.enforcement),
    )
}

fn one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn cell(text: &str) -> String {
    one_line(text).replace('|', "\\|")
}
