[package]
name = "lighthouse-rpc"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
lighthouse-spec.workspace = true
lighthouse-model.workspace = true
lighthouse-plugin.workspace = true
lighthouse-process.workspace = true
lighthouse-protocol.workspace = true
lighthouse-resource.workspace = true

[dev-dependencies]
tempfile.workspace = true
lighthouse-engine.workspace = true
lighthouse-test-support = { path = "../lighthouse-test-support" }
