//! The agent skill, generated from the catalog and the configuration so that
//! rules, config and guidance have one source.

use std::{collections::BTreeSet, fmt::Write};

use lighthouse_engine::active_rules;
use lighthouse_spec::{Catalog, tier};

use crate::{Result, Session};

/// Marks a skill file as generated: such a file may be rewritten, any other
/// is the user's and is left alone.
pub const SKILL_MARKER: &str = "<!-- generated by lighthouse; do not edit -->";

/// The fixed part of the skill: frontmatter, the loop, the rules of conduct.
const HEAD: &str = include_str!("skill-head.md");

/// The skill of the project: its catalog layers and its configuration.
pub fn skill_for(session: &Session) -> Result<String> {
    let catalog = session.catalog()?;
    let registry = session.in_process_registry()?;
    let active = active_rules(&registry, &session.config)?;
    Ok(skill(&catalog, &active))
}

/// The text of `skills/lighthouse/SKILL.md`: what Lighthouse is for, the loop
/// an agent follows, how to look rules up, and a digest (id, title, tier) of
/// the patterns `active` names. The rule text itself is never copied: the
/// agent reads it from the MCP resources or `lighthouse explain`.
pub fn skill(catalog: &Catalog, active: &BTreeSet<String>) -> String {
    let mut out = String::from(HEAD);
    let mut by_pack: Vec<(&str, Vec<String>)> = Vec::new();
    for pack in &catalog.packs {
        let lines: Vec<String> = pack
            .sections
            .iter()
            .flat_map(|s| &s.patterns)
            .filter(|p| active.contains(&p.id))
            .map(|p| {
                let level = p.severity().map_or("doc", |s| tier(s, Some(p)));
                let fixable = p
                    .fix
                    .as_ref()
                    .map_or(String::new(), |f| format!(", fixable: {}", f.safety));
                format!("- `{}` ({level}{fixable}) {}", p.id, p.title)
            })
            .collect();
        if !lines.is_empty() {
            by_pack.push((&pack.id, lines));
        }
    }
    let total: usize = by_pack.iter().map(|(_, l)| l.len()).sum();
    let _ = writeln!(out, "\n## Active patterns ({total})\n");
    out.push_str("Tiers: mechanical (error), heuristic (warn), judgment (review). `fixable: safe|suggested` marks a rule with a fixer.\n");
    for (pack, lines) in by_pack {
        let _ = writeln!(out, "\n### {pack}\n");
        for line in lines {
            let _ = writeln!(out, "{line}");
        }
    }
    out
}
