//! The agent skill, generated from the catalog and the configuration so that
//! decisions, config and guidance have one source.

use std::{collections::BTreeSet, fmt::Write};

use lighthouse_engine::active_rules;
use lighthouse_spec::{Catalog, tier};

use crate::{Result, Session};

/// Marks a skill file as generated: such a file may be rewritten, any other
/// is the user's and is left alone.
pub const SKILL_MARKER: &str = "<!-- generated by lighthouse; do not edit -->";

/// The fixed part of the skill: frontmatter, the loop, the rules of conduct.
const HEAD: &str = include_str!("skill-head.md");

/// The skill of the project: its catalog layers and its configuration.
pub fn skill_for(session: &Session) -> Result<String> {
    let catalog = session.catalog()?;
    let registry = session.in_process_registry()?;
    let active = active_rules(&registry, &session.config)?;
    Ok(skill(&catalog, &active))
}

/// The text of `skills/lighthouse/SKILL.md`: what Lighthouse is for, the loop
/// an agent follows, how to look decisions up, and a digest (id, title, tier)
/// of the decisions `active` names. The decision text itself is never copied:
/// the agent reads it from the MCP resources or `lighthouse explain`.
pub fn skill(catalog: &Catalog, active: &BTreeSet<String>) -> String {
    let mut out = String::from(HEAD);
    let mut by_pack: Vec<(&str, Vec<String>)> = Vec::new();
    for pack in &catalog.packs {
        let lines: Vec<String> = pack
            .sections
            .iter()
            .flat_map(|s| &s.decisions)
            .filter(|d| active.contains(d.id()))
            .map(|d| {
                let level = d.severity().map_or("doc", |s| tier(s, Some(d)));
                let fixable = d
                    .fix
                    .as_ref()
                    .map_or(String::new(), |f| format!(", fixable: {}", f.safety));
                format!("- `{}` ({level}{fixable}) {}", d.id(), d.title)
            })
            .collect();
        if !lines.is_empty() {
            by_pack.push((&pack.id, lines));
        }
    }
    let total: usize = by_pack.iter().map(|(_, l)| l.len()).sum();
    let _ = writeln!(out, "\n## Active decisions ({total})\n");
    out.push_str("A decision's tier is its enforcement: mechanical (default error), heuristic (default warn), judgment (default info). Heuristic and judgment findings are review tasks and verdicts can suppress them, at any severity; mechanical findings cannot be suppressed. `fixable: safe|suggested` marks a decision with a fixer.\n");
    for (pack, lines) in by_pack {
        let _ = writeln!(out, "\n### {pack}\n");
        for line in lines {
            let _ = writeln!(out, "{line}");
        }
    }
    out
}
