[package]
name = "lighthouse-spec"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
cel.workspace = true
include_dir.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_norway.workspace = true
similar.workspace = true
sha2.workspace = true
thiserror.workspace = true
lighthouse-model.workspace = true
lighthouse-plugin.workspace = true
lighthouse-resource.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
