[package]
name = "lighthouse-spec"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
cel.workspace = true
include_dir.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_norway.workspace = true
similar.workspace = true
thiserror.workspace = true
lighthouse-model.workspace = true
lighthouse-plugin.workspace = true
lighthouse-resource.workspace = true

[dev-dependencies]
lighthouse-test-support = { path = "../lighthouse-test-support" }
insta.workspace = true
tempfile.workspace = true
